/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sceneModel.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sceneModel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gums_GumsMaterial_0.geometry} material={materials.GumsMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0001.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0002.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0003.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0004.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0005.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0006.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0007.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0008.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0009.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0010.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0011.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0012.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0013.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0014.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0015.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0016.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0017.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0018.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0019.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0020.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0021.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0022.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0023.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0024.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0025.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0026.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0027.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0028.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0029.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0030.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0031.geometry} material={materials.TeethMaterial} />
      <mesh geometry={nodes.Teeth_TeethMaterial_0032.geometry} material={materials.TeethMaterial} />
    </group>
  )
}

useGLTF.preload('/sceneModel.gltf')
